name: Trigger redeploy on Netlify
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: Make POST request
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        shell: bash
        env:
          UNIQUE_STRING: ${{ secrets.6495faebe032e57a5513019e }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$UNIQUE_STRING
